### ISSUE TITLE
Does not build on Python3.11

### ISSUE THREAD

**Issue by marqrdt** [alexgorji/musicscore#2]
Hi,
   This is more of a heads-up than a bug. This module does not build on Python 3.11. It doesn't seem to be a problem with this module at all, but with the quicktions dependency, which does not appear to support 3.11 at this time.

Thanks,

Paul

**Comment by alexgorji** [comment]
Hi Paul, 
thanks for your comment. I'm running now all tests under 3.11 and don't see any issues. I created an extra repository for running tests with a fresh installation via pip for python versions 3.9, 3.10 and 3.11 (https://github.com/alexgorji/musicscore2-tests). My tests are all green. Feel free to check it out (under Actions).
Could you please let me know what exactly the problems with quicktions are and which version you are using? On my machine I'm using at the moment musicscore2==1.3.3, quicktions==1.14. and Python 3.11.4

Thanks again

Alex
